<!-- card layout generated by ChatGPT --> 
<a href="<?= BASE_URL ?>/" class="btn btn-outline-secondary mb-3">← Back</a>

<div class="row my-5 justify-content-center">
  <div class="col-md-10">
    <?php if (isset($_SESSION['user_id']) && $_SESSION['role'] === 'admin'): ?>
      <!-- Card 1: Manage Existing Cases -->
      <div class="card mb-4 shadow-sm rounded-3">
        <div class="row g-0 align-items-center">
          <div class="col-md-8 p-4">
            <h4 class="card-title">Manage Existing Cases</h4>
            <p class="card-text text-muted">
              Access and update cases already in the system, review details, and make changes as needed.
            </p>
          </div>
          <div class="col-md-4 text-end pe-4">
            <a href="<?= BASE_URL ?>/case/manage" class="btn btn-outline-primary btn-lg">Manage Cases</a>
          </div>
        </div>
      </div>

      <!-- Card 2: Add New Case -->
      <div class="card shadow-sm rounded-3">
        <div class="row g-0 align-items-center">
          <div class="col-md-8 p-4">
            <h4 class="card-title">Add New Case</h4>
            <p class="card-text text-muted">
              Begin a new case by entering details for the defendant, lawyer, charges, and court events.
            </p>
          </div>
          <div class="col-md-4 text-end pe-4">
            <a href="<?= BASE_URL ?>/case/defendant" class="btn btn-primary btn-lg">Add Case</a>
          </div>
        </div>
      </div>

    <?php else: ?>
      <!-- Card: View Existing Cases -->
      <div class="card shadow-sm rounded-3">
        <div class="row g-0 align-items-center">
          <div class="col-md-8 p-4">
            <h4 class="card-title">View Existing Cases</h4>
            <p class="card-text text-muted">
              Access and update cases already in the system, review details, and make changes as needed.
            </p>
          </div>
          <div class="col-md-4 text-end pe-4">
            <a href="<?= BASE_URL ?>/case/view" class="btn btn-outline-secondary btn-lg">View Cases</a>
          </div>
        </div>
      </div>
    <?php endif; ?>
  </div>
</div>
